# SITE SETTINGS
title: Open science lab for biodiversity
description: We make biodiversity research open and reproducible
author: oscibio team members
url: "https://oscibio.inbo.be"
baseurl: "" # Otherwise GitHub Pages will set this to "/oscibio"

# SOCIAL PROFILES
email: oscibio@inbo.be
twitter_username: oscibio
github_username: inbo

# THEME SETTINGS (ALL OPTIONAL)
theme: minima
remote_theme: peterdesmet/petridish
posts_on_home: 3
tweets_on_home: true
archive_permalink: /blog/
colors:
  links: "#356196"  # INBO blue
  banner: "#c04384" # INBO fuchsia
  footer: "#3c3c3c" # INBO gray
rounded_corners: true

# BUILD SETTINGS
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - LICENSE

# FRONTMATTER DEFAULTS
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      type: posts
    values:
      permalink: "/blog/:slug/"
